// copy/lib/cli.mjs — build/check/status/ack for the interface-string substrate.
// Every function takes the repo root so tests can run on fixture roots.
import fs from 'node:fs';
import path from 'node:path';
import { entryHash, catalogReport, reportFailures, pseudoLocalize, runtimeCatalog } from './catalog.mjs';
import { scanFile } from './scan-source.mjs';
import { xcstrings, androidStrings, androidName } from './mobile.mjs';

const read = (root, rel) => JSON.parse(fs.readFileSync(path.join(root, rel), 'utf8'));
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
export const slashKey = (command, field) => `slash.${camel(command.replace(/^\//, ''))}.${field}`;
const entryKeys = (obj) => Object.keys(obj).filter((k) => !k.startsWith('$'));

export function loadCatalog(root) {
  const dir = path.join(root, 'copy', 'messages');
  const translations = {};
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.json') && f !== 'en.json').sort()) {
    translations[file.replace(/\.json$/, '')] = read(root, `copy/messages/${file}`);
  }
  return {
    en: read(root, 'copy/messages/en.json'),
    translations,
    glossary: read(root, 'copy/glossary.json'),
    scope: read(root, 'copy/i18n-scope.json'),
    registry: read(root, 'copy/slash-commands.json'),
  };
}

const runtimeFile = (data) =>
  '// GENERATED by copy/build.mjs from copy/messages — do not edit by hand.\n'
  + "(function (root, data) { if (typeof module !== 'undefined' && module && module.exports) module.exports = data; else root.blancStrings = data; })"
  + `(typeof self !== 'undefined' ? self : this, ${JSON.stringify(data)});\n`;

export function generate(root) {
  const { en, translations, registry } = loadCatalog(root);
  const files = {};
  const pseudoTr = Object.fromEntries(entryKeys(en).map((k) => [k, { message: pseudoLocalize(en[k].message), source: 'pseudo' }]));
  const locales = [
    { code: 'en', endonym: 'English', dir: 'ltr', status: 'selectable', tr: null },
    ...Object.entries(translations).map(([code, tr]) => ({ code, endonym: tr.$meta.endonym, dir: tr.$meta.dir, status: tr.$meta.status, tr })),
    { code: 'en-XA', endonym: 'Pseudo', dir: 'ltr', status: 'pseudo', tr: pseudoTr },
  ];
  for (const l of locales) {
    files[`src/renderer/pages/strings.${l.code}.js`] = runtimeFile(runtimeCatalog({ locale: l.code, dir: l.dir, en, tr: l.tr }));
  }
  files['src/main/i18n-locales.json'] = JSON.stringify(locales.map(({ code, endonym, dir, status }) => ({ code, endonym, dir, status })), null, 2) + '\n';

  const mobileLocales = { en: Object.fromEntries(entryKeys(en).map((k) => [k, en[k].message])) };
  for (const [code, tr] of Object.entries(translations)) {
    mobileLocales[code] = runtimeCatalog({ locale: code, dir: tr.$meta.dir, en, tr }).messages;
  }
  files['copy/generated/ios/Localizable.xcstrings'] = xcstrings({ en, locales: mobileLocales });
  for (const [code, messages] of Object.entries(mobileLocales)) {
    files[`copy/generated/android/values${code === 'en' ? '' : `-${code}`}/strings.xml`] = androidStrings({ en, messages });
  }

  // Legacy English slash resources read by ios/Blanc/Blanc/SlashCommand.swift.
  const legacyKey = (command) => 'slash_' + command.replace(/^\//, '').replace(/-/g, '_');
  const mobileCommands = registry.commands.filter((c) => !c.platforms);
  files['copy/generated/SlashCommands.strings'] = '/* GENERATED by copy/build.mjs from copy/messages/en.json — do not edit by hand. */\n'
    + mobileCommands.map((c) => `"${legacyKey(c.command)}" = ${JSON.stringify(en[slashKey(c.command, 'hint')].message)};\n`).join('');
  const xmlEsc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
  files['copy/generated/slash_commands.xml'] = '<!-- GENERATED by copy/build.mjs from copy/messages/en.json — do not edit by hand. -->\n<resources>\n'
    + mobileCommands.map((c) => `    <string name="${legacyKey(c.command)}">${xmlEsc(en[slashKey(c.command, 'hint')].message)}</string>\n`).join('')
    + '</resources>\n';
  return files;
}

export function runBuild(root) {
  const written = [];
  for (const [rel, content] of Object.entries(generate(root))) {
    fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true });
    fs.writeFileSync(path.join(root, rel), content);
    written.push(rel);
  }
  return written;
}

function slashDrift(root, { en, registry }) {
  // Desktop copies stay hand-synced until phase 3 replaces them with t() calls.
  const problems = [];
  const parseTuples = (rel) => {
    if (!rel || !fs.existsSync(path.join(root, rel))) return null;
    const js = fs.readFileSync(path.join(root, rel), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
    const block = js.match(/const SLASH_COMMANDS = \[([\s\S]*?)\];/)?.[1];
    return block ? [...block.matchAll(/^\s*\['([^']+)',\s*'([^']*)'\]/gm)].map((m) => ({ command: m[1], hint: m[2] })) : null;
  };
  const overlayRel = registry.sources?.overlay;
  const expectedOverlay = registry.commands.map((c) => ({ command: c.command, hint: en[slashKey(c.command, 'hint')]?.message }));
  const expectedDoc = registry.commands.map((c) => ({
    command: c.doc?.command ?? c.command,
    hint: en[slashKey(c.command, en[slashKey(c.command, 'doc')] ? 'doc' : 'hint')]?.message,
  }));
  const compare = (name, actual, expected) => {
    if (!actual) return;
    const n = Math.max(actual.length, expected.length);
    for (let i = 0; i < n; i++) {
      const a = actual[i], e = expected[i];
      if (!a || !e || a.command !== e.command || a.hint !== e.hint) {
        problems.push(`${name} #${i}: got ${JSON.stringify(a)}, catalog says ${JSON.stringify(e)}`);
      }
    }
  };
  if (overlayRel && fs.existsSync(path.join(root, overlayRel))) {
    const js = fs.readFileSync(path.join(root, overlayRel), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
    compare('overlay.js', [...js.matchAll(/^\s*\{\s*cmd:\s*'([^']+)',\s*hint:\s*'([^']*)'/gm)].map((m) => ({ command: m[1], hint: m[2] })), expectedOverlay);
  }
  // A copy that reads its hints from the catalog keeps the registry's order
  // and uses each command's own slash.<name>.hint key.
  const keysRel = registry.sources?.overlayKeys;
  if (keysRel && fs.existsSync(path.join(root, keysRel))) {
    const js = fs.readFileSync(path.join(root, keysRel), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
    const actual = [...js.matchAll(/^\s*\{\s*cmd:\s*'([^']+)',\s*hint:\s*blancI18n\.t\('([^']+)'\)/gm)]
      .map((m) => ({ command: m[1], hint: m[2] }));
    compare(keysRel.split('/').pop(), actual, registry.commands.map((c) => ({ command: c.command, hint: slashKey(c.command, 'hint') })));
  }
  compare('shortcuts.js', parseTuples(registry.sources?.shortcuts), expectedDoc);
  // main.js lists each command's reference spelling with the catalog key of
  // its reference text (the doc key where one exists, else the hint key).
  const expectedDocKeys = registry.commands.map((c) => ({
    command: c.doc?.command ?? c.command,
    hint: slashKey(c.command, en[slashKey(c.command, 'doc')] ? 'doc' : 'hint'),
  }));
  compare('main.js', parseTuples(registry.sources?.mainKeys), expectedDocKeys);
  for (const c of registry.commands) if (!en[slashKey(c.command, 'hint')]) problems.push(`${slashKey(c.command, 'hint')} missing from en.json`);
  return problems;
}

export function runCheck(root) {
  const loaded = loadCatalog(root);
  const { failures, warnings } = reportFailures(catalogReport(loaded));
  for (const [rel, content] of Object.entries(generate(root))) {
    const p = path.join(root, rel);
    if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== content) failures.push(`STALE: ${rel} — run \`npm run copy:build\``);
  }
  const names = new Map();
  for (const key of entryKeys(loaded.en)) {
    const name = androidName(key);
    if (names.has(name)) failures.push(`Android name collision: ${key} and ${names.get(name)} → ${name}`);
    names.set(name, key);
  }
  failures.push(...slashDrift(root, loaded));
  for (const [rel, { state, allow = [] }] of Object.entries(loaded.scope.files ?? {})) {
    const p = path.join(root, rel);
    if (!fs.existsSync(p)) { failures.push(`i18n-scope: ${rel} is missing — update copy/i18n-scope.json`); continue; }
    if (state !== 'guarded') continue;
    const { problems } = scanFile(rel, fs.readFileSync(p, 'utf8'), { en: loaded.en, allow });
    failures.push(...problems.map((problem) => `${rel}: ${problem}`));
  }
  return { failures, warnings };
}

export function runStatus(root, locale) {
  const loaded = loadCatalog(root);
  const r = catalogReport(loaded).locales[locale];
  if (!r) throw new Error(`unknown locale ${locale}`);
  const line = (key) => `  ${key}\n    en:   ${JSON.stringify(loaded.en[key].message)}\n    note: ${loaded.en[key].note}`;
  return [
    `${locale} (${r.status}): ${r.covered}/${r.total} current`,
    `missing (${r.missing.length}):`, ...r.missing.map(line),
    `stale (${r.stale.length}):`, ...r.stale.map((key) => `${line(key)}\n    was:  ${JSON.stringify(loaded.translations[locale][key].message)}`),
    `invalid (${r.invalid.length}):`, ...r.invalid.map((p) => `  ${p}`),
  ].join('\n');
}

export function runAck(root, locale, keys) {
  if (!keys.length) throw new Error('copy:ack needs at least one key (there is deliberately no all-keys mode)');
  const rel = `copy/messages/${locale}.json`;
  if (!fs.existsSync(path.join(root, rel))) throw new Error(`unknown locale ${locale}`);
  const { en } = loadCatalog(root);
  const tr = read(root, rel);
  for (const key of keys) {
    if (!Object.hasOwn(en, key) || key.startsWith('$')) throw new Error(`unknown key ${key}`);
    if (typeof tr[key]?.message !== 'string') throw new Error(`${key} has no ${locale} message to acknowledge`);
  }
  for (const key of keys) tr[key].source = entryHash(en[key]);
  fs.writeFileSync(path.join(root, rel), JSON.stringify(tr, null, 2) + '\n');
}
