// copy/lib/mobile.mjs — per-locale mobile string resources from the catalog.
// One plural per message (enforced by the parser) lets each plural message
// become one full string per category.
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { parseMessage } = require('../../src/renderer/pages/i18n.js');

// Argument order = first appearance in the English message.
function argOrder(nodes, out = []) {
  for (const n of nodes) {
    if ((n.type === 'arg' || n.type === 'plural') && !out.includes(n.name)) out.push(n.name);
    if (n.type === 'tag') argOrder(n.children, out);
    if (n.type === 'plural') for (const b of Object.values(n.branches)) argOrder(b, out);
  }
  return out;
}

function flatten(nodes, order, platform, pluralName = null, branch = null) {
  return nodes.map((n) => {
    const pos = (name) => order.indexOf(name) + 1;
    if (n.type === 'text') return n.value.replace(/%/g, '%%');
    if (n.type === 'arg') return `%${pos(n.name)}$${platform === 'android' ? 's' : '@'}`;
    if (n.type === 'pound') return platform === 'android' ? `%${pos(pluralName)}$d` : `%${pos(pluralName)}$lld`;
    if (n.type === 'tag') return `<${n.index}>${flatten(n.children, order, platform, pluralName, branch)}</${n.index}>`;
    return flatten(n.branches[branch] ?? n.branches.other, order, platform, n.name, branch);
  }).join('');
}

const pluralOf = (nodes) => {
  for (const n of nodes) {
    if (n.type === 'plural') return n;
    if (n.type === 'tag') { const inner = pluralOf(n.children); if (inner) return inner; }
  }
  return null;
};

export const androidName = (key) => key.replace(/([A-Z])/g, '_$1').replace(/\./g, '_').toLowerCase();

export function xcstrings({ en, locales }) {
  const strings = {};
  for (const [key, entry] of Object.entries(en).filter(([k]) => !k.startsWith('$'))) {
    const order = argOrder(parseMessage(entry.message));
    const localizations = {};
    for (const [code, messages] of Object.entries(locales)) {
      if (typeof messages[key] !== 'string') continue;
      const nodes = parseMessage(messages[key]);
      const plural = pluralOf(nodes);
      if (!plural) {
        localizations[code] = { stringUnit: { state: 'translated', value: flatten(nodes, order, 'ios') } };
      } else {
        const variations = {};
        for (const category of Object.keys(plural.branches).filter((s) => !s.startsWith('='))) {
          variations[category] = { stringUnit: { state: 'translated', value: flatten(nodes, order, 'ios', null, category) } };
        }
        localizations[code] = { variations: { plural: variations } };
      }
    }
    strings[key] = { comment: entry.note, extractionState: 'manual', localizations };
  }
  return JSON.stringify({ sourceLanguage: 'en', strings, version: '1.0' }, null, 2) + '\n';
}

const xmlEsc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '\\"').replace(/'/g, "\\'");

export function androidStrings({ en, messages }) {
  let out = '<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by copy/build.mjs from copy/messages — do not edit by hand. -->\n<resources>\n';
  for (const key of Object.keys(en).filter((k) => !k.startsWith('$'))) {
    if (typeof messages[key] !== 'string') continue;
    const order = argOrder(parseMessage(en[key].message));
    const nodes = parseMessage(messages[key]);
    const plural = pluralOf(nodes);
    const name = androidName(key);
    if (!plural) {
      out += `    <string name="${name}">${xmlEsc(flatten(nodes, order, 'android'))}</string>\n`;
    } else {
      out += `    <plurals name="${name}">\n`;
      for (const category of Object.keys(plural.branches).filter((s) => !s.startsWith('='))) {
        out += `        <item quantity="${category}">${xmlEsc(flatten(nodes, order, 'android', null, category))}</item>\n`;
      }
      out += '    </plurals>\n';
    }
  }
  return out + '</resources>\n';
}
