// Blanc copy-catalog generator — slash commands (substrate S3).
//
//   node copy/build.mjs           emit generated/{SlashCommands.strings,slash_commands.xml}
//   node copy/build.mjs --check    verify BOTH desktop copies (overlay.js command table and
//                                  pages/shortcuts.js reference list) match slash-commands.json,
//                                  and the generated files are current. Exit 1 on drift.
//
// Same shape as tokens/ and settings-schema/: one source, desktop guarded (the two
// hand-synced JS copies are parsed and compared, not rewritten), mobile string
// resources generated so the lowercase-mono command copy never forks.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = path.join(ROOT, 'copy', 'slash-commands.json');
const OUT = path.join(ROOT, 'copy', 'generated');
const spec = JSON.parse(fs.readFileSync(SPEC, 'utf8'));

const keyFor = (command) => 'slash_' + command.replace(/^\//, '').replace(/-/g, '_');
const xmlEsc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '\\"').replace(/'/g, "\\'");

// ---- generators (mobile uses the primary `hint`) ----
function genStrings() {
  let out = '/* GENERATED by copy/build.mjs from copy/slash-commands.json — do not edit by hand. */\n';
  for (const c of spec.commands) out += `"${keyFor(c.command)}" = ${JSON.stringify(c.hint)};\n`;
  return out;
}
function genXml() {
  let out = '<!-- GENERATED by copy/build.mjs from copy/slash-commands.json — do not edit by hand. -->\n<resources>\n';
  for (const c of spec.commands) out += `    <string name="${keyFor(c.command)}">${xmlEsc(c.hint)}</string>\n`;
  out += '</resources>\n';
  return out;
}
const ARTIFACTS = { 'SlashCommands.strings': genStrings(), 'slash_commands.xml': genXml() };

// ---- parse the two desktop copies ----
function parseOverlay() {
  const js = fs.readFileSync(path.join(ROOT, spec.sources.overlay), 'utf8');
  return [...js.matchAll(/cmd:\s*'([^']+)',\s*hint:\s*'([^']*)'/g)].map((m) => ({ command: m[1], hint: m[2] }));
}
function parseShortcuts() {
  const js = fs.readFileSync(path.join(ROOT, spec.sources.shortcuts), 'utf8');
  const block = js.match(/const SLASH_COMMANDS = \[([\s\S]*?)\];/)?.[1] ?? '';
  return [...block.matchAll(/\['([^']+)',\s*'([^']*)'\]/g)].map((m) => ({ command: m[1], hint: m[2] }));
}

function diffList(name, actual, expected) {
  const problems = [];
  const n = Math.max(actual.length, expected.length);
  for (let i = 0; i < n; i++) {
    const a = actual[i], e = expected[i];
    if (!a) { problems.push(`${name}[${i}]: missing "${e.command}"`); continue; }
    if (!e) { problems.push(`${name}[${i}]: unexpected "${a.command}"`); continue; }
    if (a.command !== e.command || a.hint !== e.hint) {
      problems.push(`${name} #${i}: got {"${a.command}" / "${a.hint}"}, source says {"${e.command}" / "${e.hint}"}`);
    }
  }
  return problems;
}

function check() {
  const overlayExpected = spec.commands.map((c) => ({ command: c.command, hint: c.hint }));
  const shortcutsExpected = spec.commands.map((c) => ({ command: c.doc?.command ?? c.command, hint: c.doc?.hint ?? c.hint }));
  const problems = [
    ...diffList('overlay.js', parseOverlay(), overlayExpected),
    ...diffList('shortcuts.js', parseShortcuts(), shortcutsExpected),
  ];

  let failed = problems.length > 0;
  if (failed) console.error('DRIFT (desktop copy vs slash-commands.json):\n' + problems.map((p) => '  ' + p).join('\n'));

  for (const [name, content] of Object.entries(ARTIFACTS)) {
    const p = path.join(OUT, name);
    const onDisk = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (onDisk !== content) { failed = true; console.error(`STALE: copy/generated/${name} — run \`npm run copy:build\``); }
  }

  if (failed) { console.error('\ncopy:check failed.'); process.exit(1); }
  console.log('copy:check OK — both desktop copies match the source, generated files current.');
}

function build() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, content] of Object.entries(ARTIFACTS)) {
    fs.writeFileSync(path.join(OUT, name), content);
    console.log(`wrote copy/generated/${name}`);
  }
}

process.argv.includes('--check') ? check() : build();
