// Blanc copy-catalog generator (substrate S3).
//
//   node copy/build.mjs           emit generated/{SlashCommands.strings,slash_commands.xml,
//                                                 IslandActions.strings,island_actions.xml}
//   node copy/build.mjs --check    verify the desktop copies match the catalogs and the
//                                  generated files are current. Exit 1 on drift.
//
// Two catalogs, same posture as tokens/ and settings-schema/: one source, desktop
// guarded (the hand-synced JS is parsed and compared, not rewritten), mobile
// string resources generated so the copy never forks.
//
//   slash-commands.json  — all THREE desktop copies (overlay.js command table,
//                          pages/shortcuts.js reference list, main.js Help-menu
//                          SLASH_COMMANDS) are diffed entry-for-entry.
//   island-actions.json  — the Island action titles (iPhone Duo's vertical toolbar
//                          needs a title per item, D27). Each entry names the base
//                          label the desktop files already carry; the guard checks
//                          that literal is still present in a label-bearing
//                          statement of that file. One-way by design: desktop has
//                          many more labels than the catalog covers.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'copy', 'generated');
const readJson = (rel) => JSON.parse(fs.readFileSync(path.join(ROOT, 'copy', rel), 'utf8'));
const spec = readJson('slash-commands.json');
const actions = readJson('island-actions.json');

const keyFor = (command) => 'slash_' + command.replace(/^\//, '').replace(/-/g, '_');
const xmlEsc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '\\"').replace(/'/g, "\\'");
const stripComments = (js) => js.replace(/\/\*[\s\S]*?\*\//g, '');
const forPlatform = (entries, platform) => entries.filter((e) => !e.platforms || e.platforms.includes(platform));

// ---- generators: slash commands (mobile uses the primary `hint`) ----
function genStrings() {
  let out = '/* GENERATED by copy/build.mjs from copy/slash-commands.json — do not edit by hand. */\n';
  for (const c of spec.commands.filter((entry) => !entry.platforms)) {
    out += `"${keyFor(c.command)}" = ${JSON.stringify(c.hint)};\n`;
  }
  return out;
}
function genXml() {
  let out = '<!-- GENERATED by copy/build.mjs from copy/slash-commands.json — do not edit by hand. -->\n<resources>\n';
  for (const c of spec.commands.filter((entry) => !entry.platforms)) {
    out += `    <string name="${keyFor(c.command)}">${xmlEsc(c.hint)}</string>\n`;
  }
  out += '</resources>\n';
  return out;
}

// ---- generators: island actions (title per item; symbol recorded for iOS) ----
function genActionStrings() {
  let out = '/* GENERATED by copy/build.mjs from copy/island-actions.json — do not edit by hand.\n' +
            '   Island action titles (D27). Each line notes the SF Symbol the catalog pairs with it. */\n';
  for (const a of forPlatform(actions.actions, 'ios')) {
    out += `"island_${a.id}" = ${JSON.stringify(a.title)}; /* ${a.symbol} */\n`;
  }
  return out;
}
function genActionXml() {
  let out = '<!-- GENERATED by copy/build.mjs from copy/island-actions.json — do not edit by hand.\n' +
            '     Island action titles (D27). -->\n<resources>\n';
  for (const a of forPlatform(actions.actions, 'android')) {
    out += `    <string name="island_${a.id}">${xmlEsc(a.title)}</string>\n`;
  }
  out += '</resources>\n';
  return out;
}

const ARTIFACTS = {
  'SlashCommands.strings': genStrings(),
  'slash_commands.xml': genXml(),
  'IslandActions.strings': genActionStrings(),
  'island_actions.xml': genActionXml(),
};

// ---- parse the desktop slash-command copies ----
// Parsers strip /* */ block comments and anchor to line start (^\s*, /m) so a
// commented-out command entry can't be read as a live one and let drift pass.
function parseOverlay() {
  const js = stripComments(fs.readFileSync(path.join(ROOT, spec.sources.overlay), 'utf8'));
  return [...js.matchAll(/^\s*\{\s*cmd:\s*'([^']+)',\s*hint:\s*'([^']*)'/gm)].map((m) => ({ command: m[1], hint: m[2] }));
}
// shortcuts.js and main.js each hold a `const SLASH_COMMANDS = [ ['cmd','hint'], … ]`
// in the doc-override spelling — parse either by its spec.sources key.
function parseTupleList(sourceKey) {
  const js = stripComments(fs.readFileSync(path.join(ROOT, spec.sources[sourceKey]), 'utf8'));
  const block = js.match(/const SLASH_COMMANDS = \[([\s\S]*?)\];/)?.[1] ?? '';
  return [...block.matchAll(/^\s*\['([^']+)',\s*'([^']*)'\]/gm)].map((m) => ({ command: m[1], hint: m[2] }));
}

function diffList(name, actual, expected) {
  const problems = [];
  const n = Math.max(actual.length, expected.length);
  for (let i = 0; i < n; i++) {
    const a = actual[i], e = expected[i];
    if (!a) { problems.push(`${name}[${i}]: missing "${e.command}"`); continue; }
    if (!e) { problems.push(`${name}[${i}]: unexpected "${a.command}"`); continue; }
    if (a.command !== e.command || a.hint !== e.hint) {
      problems.push(`${name} #${i}: got {"${a.command}" / "${a.hint}"}, source says {"${e.command}" / "${e.hint}"}`);
    }
  }
  return problems;
}

// ---- guard the desktop Island action labels ----
// A label counts as present when a label-bearing line (a `title`/`aria-label`
// assignment or attribute, or a pillButton(...) call) carries it as the start of
// a quoted string: exactly the label, or the label followed by ` (` for a
// shortcut suffix such as `'New tab (⌘T)'` / `` `New tab (${modKey}T)` ``.
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
function labelPresent(js, label) {
  const lit = new RegExp(`(['"\`])${escapeRe(label)}(?:\\1| \\()`);
  return stripComments(js).split('\n').some((line) =>
    /\btitle\b|aria-label|pillButton\(/.test(line) && lit.test(line));
}
function checkActions() {
  const problems = [];
  const files = new Map();
  for (const [key, rel] of Object.entries(actions.sources)) files.set(key, fs.readFileSync(path.join(ROOT, rel), 'utf8'));
  for (const a of actions.actions) {
    if (a.platforms) continue;
    if (!a.desktop || !Object.keys(a.desktop).length) { problems.push(`island-actions "${a.id}": no desktop guard and no platforms allowlist`); continue; }
    for (const [key, label] of Object.entries(a.desktop)) {
      const js = files.get(key);
      if (js === undefined) { problems.push(`island-actions "${a.id}": unknown desktop source "${key}"`); continue; }
      if (!labelPresent(js, label)) problems.push(`${actions.sources[key]}: label "${label}" for island action "${a.id}" not found in any title/aria-label/pillButton statement`);
    }
  }
  return problems;
}

function check() {
  const overlayExpected = spec.commands.map((c) => ({ command: c.command, hint: c.hint }));
  const shortcutsExpected = spec.commands.map((c) => ({ command: c.doc?.command ?? c.command, hint: c.doc?.hint ?? c.hint }));
  const problems = [
    ...diffList('overlay.js', parseOverlay(), overlayExpected),
    ...diffList('shortcuts.js', parseTupleList('shortcuts'), shortcutsExpected),
    ...diffList('main.js', parseTupleList('main'), shortcutsExpected),
    ...checkActions(),
  ];

  let failed = problems.length > 0;
  if (failed) console.error('DRIFT (desktop copy vs copy/*.json):\n' + problems.map((p) => '  ' + p).join('\n'));

  for (const [name, content] of Object.entries(ARTIFACTS)) {
    const p = path.join(OUT, name);
    const onDisk = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (onDisk !== content) { failed = true; console.error(`STALE: copy/generated/${name} — run \`npm run copy:build\``); }
  }

  if (failed) { console.error('\ncopy:check failed.'); process.exit(1); }
  console.log('copy:check OK — all three desktop slash-command copies and the Island action labels match the source, generated files current.');
}

function build() {
  fs.mkdirSync(OUT, { recursive: true });
  for (const [name, content] of Object.entries(ARTIFACTS)) {
    fs.writeFileSync(path.join(OUT, name), content);
    console.log(`wrote copy/generated/${name}`);
  }
}

process.argv.includes('--check') ? check() : build();
