#!/usr/bin/env node
// Dark websites: generate the session preload from the pinned Dark Reader
// engine and Blanc's templates.
//
//   node dark-reader/build.mjs           write src/main/dark-websites-preload.js
//   node dark-reader/build.mjs --check   verify the pinned bytes and that the
//                                        committed preload is current
//
// Updating Dark Reader is a reviewed change: download the npm tarball, check
// its integrity against the registry, copy package/darkreader.js and
// package/LICENSE (as darkreader-LICENSE.txt) into this directory, update pinned.json, then rebuild.

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const OUTPUT = 'src/main/dark-websites-preload.js';
const ENGINE_MARKER = '/*__DARK_READER_ENGINE__*/';

const policy = require('../src/main/dark-websites.js');

const read = (relative) => fs.readFileSync(path.join(here, relative));
const sha256 = (bytes) => crypto.createHash('sha256').update(bytes).digest('hex');

function verifyPinned() {
  const pinned = JSON.parse(read('pinned.json'));
  for (const [relative, expected] of Object.entries(pinned.files)) {
    const actual = sha256(read(relative));
    if (actual !== expected) {
      throw new Error(`dark-reader/${relative} sha256 ${actual} does not match pinned.json ${expected}`);
    }
  }
  return pinned;
}

function replaceOnce(source, marker, value) {
  const at = source.indexOf(marker);
  if (at < 0 || source.indexOf(marker, at + marker.length) >= 0) {
    throw new Error(`template must contain ${marker} exactly once`);
  }
  return source.slice(0, at) + value + source.slice(at + marker.length);
}

export function generate() {
  const pinned = verifyPinned();
  const engine = read('upstream/darkreader.js').toString('utf8');
  const world = replaceOnce(read('world.template.js').toString('utf8'), ENGINE_MARKER, engine);
  let preload = read('preload.template.js').toString('utf8');
  preload = replaceOnce(preload, '__WORLD_ID__', String(policy.DARK_WEBSITES_WORLD_ID));
  preload = replaceOnce(preload, '__GET_CHANNEL__', JSON.stringify(policy.GET_CHANNEL));
  preload = replaceOnce(preload, '__UPDATE_CHANNEL__', JSON.stringify(policy.UPDATE_CHANNEL));
  preload = replaceOnce(preload, '__FETCH_CHANNEL__', JSON.stringify(policy.FETCH_CHANNEL));
  preload = replaceOnce(preload, '__ENGINE_WORLD_SOURCE__', JSON.stringify(world));
  const header = [
    `// GENERATED by dark-reader/build.mjs from dark-reader/preload.template.js,`,
    `// dark-reader/world.template.js and Dark Reader ${pinned.version} (${pinned.license},`,
    `// ${pinned.homepage}). Do not edit; run npm run darkreader:build.`,
    '',
  ].join('\n');
  return header + preload;
}

function main() {
  const check = process.argv.includes('--check');
  const expected = generate();
  const target = path.join(root, OUTPUT);
  if (check) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (current !== expected) {
      throw new Error(`${OUTPUT} is stale; run npm run darkreader:build`);
    }
    console.log('darkreader:check OK — pinned engine verified, preload current.');
  } else {
    fs.writeFileSync(target, expected);
    console.log(`darkreader:build wrote ${OUTPUT} (${Buffer.byteLength(expected)} bytes).`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(`darkreader: ${err.message}`);
    process.exitCode = 1;
  }
}
