const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..', '..');
const PUBLIC = path.join(ROOT, 'site/public');

/* The share cards are generated by site/scripts/render-og-cards.mjs from each
 * feature page's own Island figure. Before that they were hand-authored and had
 * drifted: two were byte-identical to each other, two were 2784x1824 while
 * BaseLayout told every crawler they were 1200x630, and one was a small pill on
 * an otherwise empty field. These assertions are the drift alarm. */
const CARDS = [
  'og-image.png',
  'feature-island.png',
  'feature-ad-blocking.png',
  'feature-command-palette.png',
  'feature-private-tabs.png',
  'feature-tab-groups.png',
];

function png(relativePath) {
  const bytes = fs.readFileSync(path.join(PUBLIC, relativePath));
  assert.equal(bytes.subarray(1, 4).toString('ascii'), 'PNG', `${relativePath} is not a PNG`);
  return { bytes, width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

test('every Open Graph card matches the dimensions BaseLayout declares', () => {
  const layout = fs.readFileSync(path.join(ROOT, 'site/src/layouts/BaseLayout.astro'), 'utf8');
  const declaredWidth = layout.match(/og:image:width" content="(\d+)"/)?.[1];
  const declaredHeight = layout.match(/og:image:height" content="(\d+)"/)?.[1];
  assert.equal(declaredWidth, '1200');
  assert.equal(declaredHeight, '630');

  for (const card of CARDS) {
    const { width, height } = png(card);
    assert.deepEqual(
      { width, height },
      { width: Number(declaredWidth), height: Number(declaredHeight) },
      `${card} is ${width}x${height} but the meta tag promises ${declaredWidth}x${declaredHeight}`
    );
  }
});

test('each feature page ships its own distinct share card', () => {
  const digests = new Map();
  for (const card of CARDS) {
    const digest = crypto.createHash('sha256').update(png(card).bytes).digest('hex');
    const clash = digests.get(digest);
    // og-image.png intentionally reuses the Island figure, but it is a separate
    // render with the homepage's headline, so even that one differs.
    assert.equal(clash, undefined, `${card} is byte-identical to ${clash}`);
    digests.set(digest, card);
  }
});

test('the OG cards are generated, not hand-placed', () => {
  const generator = path.join(ROOT, 'site/scripts/render-og-cards.mjs');
  assert.equal(fs.existsSync(generator), true);
  const source = fs.readFileSync(generator, 'utf8');
  for (const card of CARDS) {
    assert.match(source, new RegExp(`out: '${card.replace('.', '\\.')}'`), `${card} is not in the generator`);
  }
  // Blanc's own press guidance: a visual must not turn another website's brand
  // into the story. The cards drop the page render behind the Island for that
  // reason — losing this would put a third party's wordmark on every share.
  assert.match(source, /\.demo-shot, \$\{card\.figure\} \.demo-page \{ display: none/);
});

test('the card generators set their titles in Newsreader, the site display face', () => {
  for (const script of ['site/scripts/render-og-cards.mjs', 'site/scripts/render-press-primary-capture.mjs']) {
    const source = fs.readFileSync(path.join(ROOT, script), 'utf8');
    assert.match(source, /newsreader-latin-opsz-normal\.woff2/, `${script} embeds the Newsreader file`);
    assert.match(source, /@font-face \{ font-family: Newsreader;/, `${script} declares the face`);
    assert.match(source, /h1 \{[^}]*font-family: Newsreader[^}]*font-weight: 400/, `${script} sets the title at regular weight`);
    assert.doesNotMatch(source, /h1 \{[^}]*font-weight: 600/, `${script} no longer sets a bold title`);
  }
});
